package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */

@Entity
@Table(name = "CURSOS")
public class Curso  implements java.io.Serializable {

    @Id
     private int id;
     private String nombre;
     private String nemonico;
     private Set<Estudiante> estudiantes = new HashSet<>(0);

    public Curso() {
    }

	
    public Curso(int id, String nombre, String nemonico) {
        this.id = id;
        this.nombre = nombre;
        this.nemonico = nemonico;
    }
    
    public Curso(int id, String nombre, String nemonico, Set<Estudiante> estudianteses) {
       this.id = id;
       this.nombre = nombre;
       this.nemonico = nemonico;
       this.estudiantes = estudianteses;
    }


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="nemonico", nullable=false, length=45)
    public String getNemonico() {
        return this.nemonico;
    }
    
    public void setNemonico(String nemonico) {
        this.nemonico = nemonico;
    }

    @ManyToMany(mappedBy = "cursos")
    public Set<Estudiante> getEstudianteses() {
        return this.estudiantes;
    }
    
    public void setEstudianteses(Set<Estudiante> estudianteses) {
        this.estudiantes = estudianteses;
    }




}


