package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
@Entity
@Table(name = "ESTUDIANTES")
public class Estudiante  implements java.io.Serializable {

    @Id
     private int codigo;
     private String nombre;
     private Set<Curso> cursos = new HashSet<>(0);

    public Estudiante() {
    }

	
    public Estudiante(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Estudiante(int codigo, String nombre, Set cursos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.cursos = cursos;
    }
    @Column(name="codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @ManyToMany(cascade = ALL)
    @JoinTable(name="ESTUDIANTES_CURSOS",
            joinColumns=
            @JoinColumn(name="ESTUDIANTES_codigo", referencedColumnName="codigo"),
            inverseJoinColumns=
            @JoinColumn(name="CURSOS_id", referencedColumnName="id")
    )
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


